version: '3.8'

services:
  storage:
    image: mongo:6.0.5
  elasticsearch:
    image: elasticsearch:8.8.1
  kibana:
    image: kibana:8.8.1
  redis:
    image: redis:7.0.10

  dashboard:
    image: ${DOCKER_REGISTRY-}dashboard
    build:
      context: .
      dockerfile: Services/Dashboard/Dockerfile

  databaseservice:
    image: databaseservice
    build:
      context: .
      dockerfile: Services/Database/DatabaseService/Dockerfile

  authservice:
    image: authservice
    build:
      context: .
      dockerfile: Services/Auth/AuthService/Dockerfile